export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  SIGNUP_REQUEST: "SIGNUP_REQUEST",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
};

export const categoryContants = {
  GET_ALL_CATEGORIES_REQUEST: "GET_ALL_CATEGORIES_REQUEST",
  GET_ALL_CATEGORIES_SUCCESS: "GET_ALL_CATEGORIES_SUCCESS",
  GET_ALL_CATEGORIES_FAILURE: "GET_ALL_CATEGORIES_FAILURE",
};

export const locationContants = {
  GET_ALL_LOCATION_REQUEST: "GET_ALL_LOCATION_REQUEST",
  GET_ALL_LOCATION_SUCCESS: "GET_ALL_LOCATION_SUCCESS",
  GET_ALL_LOCATION_FAILURE: "GET_ALL_LOCATION_FAILURE",
};

export const storeContants = {
  GET_ALL_STORE_REQUEST: "GET_ALL_STORE_REQUEST",
  GET_ALL_STORE_SUCCESS: "GET_ALL_STORE_SUCCESS",
  GET_ALL_STORE_FAILURE: "GET_ALL_STORE_FAILURE",
  GET_ALL_NEW_STORE_SUCCESS: "GET_ALL_NEW_STORE_SUCCESS",
  ADD_NEW_STORE_REQUEST: "ADD_NEW_STORE_REQUEST",
  ADD_NEW_STORE_SUCCESS: "ADD_NEW_STORE_SUCCESS",
  ADD_NEW_STORE_FAILURE: "ADD_NEW_STORE_FAILURE",

  GET_STORE_DETAILS_BY_ID_REQUEST: "GET_STORE_DETAILS_BY_ID_REQUEST",
  GET_STORE_DETAILS_BY_ID_SUCCESS: "GET_STORE_DETAILS_BY_ID_SUCCESS",
  GET_STORE_DETAILS_BY_ID_FAILURE: "GET_STORE_DETAILS_BY_ID_FAILURE",
};

export const userInitialdata = {
  GET_USER_DETAILS_SUCCESS: "GET_USER_DETAILS_SUCCESS",
  GET_USER_DETAILS_FAILURE: "GET_USER_DETAILS_FAILURE",
};

export const userStoreData = {
  GET_USER_STORE_DETAILS_SUCCESS: "GET_USER_STORE_DETAILS_SUCCESS",
  GET_USER__STORE_DETAILS_FAILURE: "GET_USER__STORE_DETAILS_FAILURE",
};

export const productContants = {
  GET_ALL_PRODUCTS_REQUEST: "GET_ALL_PRODUCTS_REQUEST",
  GET_ALL_PRODUCTS_SUCCESS: "GET_ALL_PRODUCTS_SUCCESS",
  GET_ALL_PRODUCTS_FAILURE: "GET_ALL_PRODUCTS_FAILURE",
  ADD_NEW_PRODUCT_REQUEST: "ADD_NEW_PRODUCT_REQUEST",
  ADD_NEW_PRODUCT_SUCCESS: "ADD_NEW_PRODUCT_SUCCESS",
  ADD_NEW_PRODUCT_FAILURE: "ADD_NEW_PRODUCT_FAILURE",
  DELETE_PRODUCT_BY_ID_REQUEST: "DELETE_PRODUCT_BY_ID_REQUEST",
  DELETE_PRODUCT_BY_ID_SUCCESS: "DELETE_PRODUCT_BY_ID_SUCCESS",
  DELETE_PRODUCT_BY_ID_FAILURE: "DELETE_PRODUCT_BY_ID_FAILURE",
  EDIT_PRODUCT_BY_ID_REQUEST: "EDIT_PRODUCT_BY_ID_REQUEST",
  EDIT_PRODUCT_BY_ID_SUCCESS: "EDIT_PRODUCT_BY_ID_SUCCESS",
  EDIT_PRODUCT_BY_ID_FAILURE: "EDIT_PRODUCT_BY_ID_FAILURE",
};

export const followContants = {
  ADD_NEW_FOLLOWING_REQUEST: "ADD_NEW_FOLLOWING_REQUEST",
  ADD_NEW_FOLLOWING_SUCCESS: "ADD_NEW_FOLLOWING_SUCCESS",
  ADD_NEW_FOLLOWING_FAILURE: "ADD_NEW_FOLLOWING_FAILURE",

  GET_ALL_FOLLOWING_REQUEST: "GET_ALL_FOLLOWING_REQUEST",
  GET_ALL_FOLLOWING_SUCCESS: "GET_ALL_FOLLOWING_SUCCESS",
  GET_ALL_FOLLOWING_FAILURE: "GET_ALL_FOLLOWING_FAILURE",

  GET_ALL_FOLLOWING_PRODUCTS_REQUEST: "GET_ALL_FOLLOWING_PRODUCTS_REQUEST",
  GET_ALL_FOLLOWING_PRODUCTS_SUCCESS: "GET_ALL_FOLLOWING_PRODUCTS_SUCCESS",
  GET_ALL_FOLLOWING_PRODUCTS_FAILURE: "GET_ALL_FOLLOWING_PRODUCTS_FAILURE",

  GET_ALL_FOLLOWING_STORE_REQUEST: "GET_ALL_FOLLOWING_STORE_REQUEST",
  GET_ALL_FOLLOWING_STORE_SUCCESS: "GET_ALL_FOLLOWING_STORE_SUCCESS",
  GET_ALL_FOLLOWING_STORE_FAILURE: "GET_ALL_FOLLOWING_STORE_FAILURE",
};


export const cartConstants = {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS: "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE: "ADD_TO_CART_FAILURE",
  RESET_CART: "RESET_CART",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};
